config/routes.rb
Rails.application.routes.draw do
  devise_for :views
  devise_for :users

resources :users, only: [:show]

  # ... (autres routes)

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "home#index" unless Rails.application.routes.named_routes[:root]

  resources :activities

  get 'activities/new/:activity_name', to: 'activities#new', as: 'create_activity'
  get 'activities/edit/:id', to: 'activities#edit', as: 'custom_edit_activity'
  
  delete 'activities/:id', to: 'activities#destroy', as: 'custom_delete_activity'



end

app/models/activity.rb
# app/models/activity.rb
class Activity < ApplicationRecord
    belongs_to :user
  end
  
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
# app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         attr_accessor :first_name, :last_name, :date_of_birth, :email, :password, :password_confirmation, :remember_me
  has_many :activities
  has_one :profile
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_user!

  def index
    # Afficher uniquement les activités de l'utilisateur actuellement connecté
    @activities = current_user.activities
  end

  def show
    # Récupérer l'activité à partir de l'ID et afficher
    @activity = current_user.activities.find(params[:id])
  end

  def new
    # Logique pour la création d'une activité
    puts "Current User: #{current_user.inspect}" 
    @activity = current_user.activities.build
    @activity.name = params[:activity_name]
  end

  def create
    @activity = current_user.activities.build(activity_params)

    if @activity.save
      redirect_to @activity
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @activity = current_user.activities.find(params[:id])
  end

  def update
    @activity = current_user.activities.find(params[:id])

    if @activity.update(activity_params)
      redirect_to @activity
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @activity = current_user.activities.find(params[:id])

    if @activity.destroy
      redirect_to activities_path, notice: 'Activity was successfully deleted.'
    else
      redirect_to activities_path, alert: 'Failed to delete activity.'
    end
  end
  
  private

  def activity_params
    params.require(:activity).permit(:name, :date_and_time, :comments, :duration)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # helper_method :current_user
  
    # def current_user
    #   # Your logic to retrieve the current user, for example, if using Devise:
    #   @current_user ||= current_user
    # end
    # app/controllers/application_controller.rb
  before_action :authenticate_user!, only: [:show]

  def show
    @user = current_user
  end
end

  

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
      render
    end
  end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/activities/edit.html.erb
<div class="activity-form">
  <h2>Edit <%= @activity.name %> Activity</h2>
  <%= form_for @activity, url: activity_path(@activity), method: :patch do |form| %>
    <%= form.hidden_field :user_id %>

    <div class="form-group">
      <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>

   <div class="form-group">
      <%= form.label :date_and_time, class: 'form-label' %>
      <%= form.datetime_select :date_and_time, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :duration, class: 'form-label' %>
      <%= form.number_field :duration, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :comments, class: 'form-label' %>
      <%= form.text_area :comments, class: 'form-control' %>
    </div>

    <%= form.submit 'Update Activity', class: 'btn-primary' %>
    <%= link_to 'Delete Activity', custom_delete_activity_path(@activity), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn-secondary' %>

  <% end %>
</div>

app/views/activities/index.html.erb
<h1 class="activitytitle">Activities</h1>

<section>
  <h2 class="activitytitleh2">Select an Activity</h2>
  <div class="activity-cards-container">
    <% activity_names = ['swimming', 'running', 'walking', 'cycling', 'weightlifting', 'yoga', 'pilates', 'hiking', 'boxing', 'golf', 'dancing', 'gymnastic'] %>
    <% activity_names.each do |activity_name| %>
      <div class="activity-card">
        <% image_path = "#{activity_name}.svg" %>
        <%= link_to new_activity_path(activity_name: activity_name) do %>
          <%= image_tag(image_path, width: 80, height: 80, class: 'activity-image') %>
          <span class="activity-title"><%= activity_name.capitalize %></span>
        <% end %>
      </div>
    <% end %>
  </div>
</section>

<style>
  .activity-cards-container {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-around; /* Adjusted to space-around */
    margin-left: 550px;
    margin-right: 550px;
  }

  .activity-card {
    text-align: center;
    margin: 10px;
    padding: 10px;
    border: 1px solid #ddd;
    border-radius: 5px;
    text-decoration: none;
    width: 110px;
  }

  .activity-image {
    width: 80px; /* Set explicit width */
    height: 80px; /* Set explicit height */
    object-fit: cover; /* Maintain aspect ratio */
  }

  .activity-card a {
    text-decoration: none; /* Remove underlines from links within activity cards */
  }

  .activity-title {
    display: block;
    margin-top: 5px;
    text-decoration: none !important; /* Désactiver le soulignement */
    color:#ad4d0e; /* Choisir la couleur orange foncé */
    font-weight: bold; /* Mettre le texte en gras */
  }
  
 /* Add additional styles for responsiveness */
  @media screen and (max-width: 1280px) {
  .activity-cards-container {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-around; /* Adjusted to space-around */
    margin-left: 0px;
    margin-right: 0px;
  }
  }
</style>

<section>
  <!-- Tableau pour afficher les activités existantes -->
  <h2 class="activitytitleh2">Existing Activities</h2>

  <div class="table-container">
    <table class="activity-table2">
      <thead>
        <tr>
          <th>Activity Name</th>
          <th>Date and Time</th>
          <th>Comments</th>
          <th>Modify</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        <% @activities.each do |activity| %>
          <tr>
            <td><%= link_to activity.name, activity_path(activity), class: 'linktitle' %></td>
            <td><%= link_to activity.date_and_time.strftime('%d-%m-%Y %Hh%M'), activity_path(activity), class: 'link' if activity.date_and_time %></td>
            <td><%= link_to activity.comments, activity_path(activity), class: 'link' %></td>
            <td><%= link_to 'Modify', edit_activity_path(activity), class: 'link' %></td>
            <td>
              <%= link_to image_tag('delete_icon.png', width: 20, height: 20),
                          custom_delete_activity_path(activity),
                          method: :delete,
                          data: { confirm: 'Are you sure?' },
                          class: 'delete-icon' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</section>

<style>
 .table-container {
    overflow-x: auto;
    margin: 20px auto; 
    padding-bottom: 20px; 
    max-width: 800px; 
  }
  .linktitle {
    text-decoration:none;
    color: #26272b;
    font-weight: bold;
  }
  .activity-table2 {
    border: 1px solid #ddd;
    border-collapse: collapse;
    margin: 0;
    padding: 0;
    width: 100%;
    background-color: #f4f4f4; 
  }

  .activity-table2 caption {
    font-size: 1.5em;
    margin: .5em 0 .75em;
  }

  .activity-table2 tr {
    background-color: #f8f8f8;
    border: 1px solid #ddd;
    padding: .5em; /* Adjust cell padding */
  }

  .activity-table2 th,
  .activity-table2 td {
    padding: .75em; /* Adjust cell padding */
    text-align: center;
    }

  .activity-table2 th {
    font-size: .85em;
    letter-spacing: .1em;
    text-transform: uppercase;
    background-color:#ddd;
    color:#ad4d0e;
    width: fit; 
    height: 50px;
  }

  .activity-table th:first-child,
  .activity-table td:first-child {
    width: 100px;
  }

  @media screen and (max-width: 600px) {
 .table-container {
    overflow-x: auto;
    margin: 20px 20px; /* Adjust margin as needed */
    padding-bottom: 20px; /* Add space below the table */
    max-width: 600px; /* Adjust max-width as needed */
  }

    .activity-table th,
    .activity-table td {
      padding: 10px; 
    }

    .activity-cell {
      width: 20%; /* Adjust as needed based on the number of columns you want on small screens */
    }

    .activity-table2 {
      border: 1px solid #ccc;
      margin: 0 auto; 
      background-color: #f0f0f0; 
    }

    .activity-table2 caption {
      font-size: 1.3em;
    }

    .activity-table2 thead {
      border: none;
      clip: rect(0 0 0 0);
      height: 1px;
      margin: -1px;
      overflow: hidden;
      padding: 10;
      position: absolute;
      width: 1px;
      color: dark;
    }

    .activity-table2 tr {
      border-bottom: 3px solid #ad4d0e;
      display: block;
      margin-bottom: .625em;
    }

    .activity-table2 td {
      border-bottom: 1px solid #ddd;
      display: block;
      font-size: .8em;
      text-align: left;
    }

    .activity-table2 td::before {
      content: attr(data-label);
      float: left;
      font-weight: bold;
      text-transform: uppercase;
    }

    .activity-table2 td:last-child {
      border-bottom: 0;
    }
  }
</style>

app/views/activities/new.html.erb
<div class="activity-form">



  <h2>Create a new <%= @activity.name %> activity</h2>
 <%= form_with(model: @activity, data: { turbo_frame: 'new_activity' }) do |form| %>


  <%= form.hidden_field :userid %>

  <div class="form-group">
    <div class="field">
      <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>
  </div>

    <div class="form-group">
      <div class="field">
        <%= form.label :date_and_time, class: 'form-label' %>
         <%= form.datetime_field :date_and_time %>
      </div>
    </div>

    <div class="form-group">
  <%= form.label :duration, class: 'form-label' do %>
    Duration in minutes:
  <% end %>
  <%= form.number_field :duration, class: 'form-control', min: 0 %>
</div>


    <div class="form-group">
      <%= form.label :comments, class: 'form-label' %>
      <%= form.text_area :comments, class: 'form-control' %>
    </div>

      <%= form.submit 'Create activity', class: 'btn-primary' %>
  <%= link_to 'Back to Activities', activities_path, class: 'btn-secondary' %>
<% end %>

  <ul>


</div>

app/views/activities/show.html.erb
<!-- app/views/activities/show.html.erb -->
<h1 class="activitytitle"><%= @activity.name %></h1>
<table class="activity-table">
 <tr>
  <td>Date:</td>
  <td><%= @activity.date_and_time.strftime('%d-%m-%Y %Hh%M') if @activity.date_and_time%></td>
</tr>

  <tr>
    <td>Duration:</td>
    <td><%= @activity.duration %> minutes</td>
  </tr>
  <tr>
    <td>Comments:</td>
    <td><%= @activity.comments %></td>
  </tr>
  <tr>
    <td><%= link_to 'Back to Activities', activities_path, class: 'btn-primary' %>
</td>
    <td><%= link_to 'Delete Activity', custom_delete_activity_path(@activity), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn-secondary' %>
</td>
    </tr>
</table>

<%= turbo_include_tags %>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fitness Tracker</title>
    <%= stylesheet_link_tag 'home', media: 'all' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8sh+Wy3vZNU2R9i6pAegIS0MpgJj5b25L"
        crossorigin="anonymous">
</head>

<body>
    <header class="jumbotron text-center">
        <h1 class="display-4">Achieve Your Fitness Goals</h1>
        <p class="lead">Track your activities and stay motivated on your fitness journey.</p>
    </header>
    <div class="container">
        <section class="about-section text-center" id="about">
            <h2 class='activitytitle'>What is Move and Groove ? </h2>
            <p>Seamlessly blending technology with health, our user-friendly platform empowers you to effortlessly log
                and track your physical activities. With a secure authentication system, personalized activity logging,
                and a sleek design, Move and Groove is your passport to a healthier lifestyle. Sign up now and embark on
                a fitness journey that's as unique as you are. Let's move and groove together towards a fitter,
                happier you! 💪🏃‍♀️ #MoveAndGroove #FitnessCompanion</p>
            <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
        </section>
    </div>

    <div class="select-activity-section">
        <h2 class='activitytitle'>Start to select an activity</h2>
        <%= link_to "DASHBOARD", activities_path, class: "btn-secondary" %>
    </div>

   <div class="third-picture-section text-center">
  <%= image_tag('home1.png', class: 'responsive-image') %>
  <!-- Content for the third section -->
</div>


    <!-- Link Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-eMNCO9rFof7gtm5ofqWWqO/47jRbdN5S02G3J5k4JzIS7PVOz2zKgO1pExXxhqb"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8sh+Wy3vZNU2R9i6pAegIS0MpgJj5b25L"
        crossorigin="anonymous"></script>
</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= turbo_include_tags %>
    <%= stylesheet_link_tag 'home', media: 'all' %>
    <%= stylesheet_link_tag "application", "home", "data-turbo-track": "reload" %> 
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8sh+Wy3vZNU2R9i6pAegIS0MpgJj5b25L" crossorigin="anonymous">
  <!-- In the head of your layout or on the home page -->
<script>
  document.addEventListener("DOMContentLoaded", function() {
    document.querySelectorAll('a[href^="#"]').forEach(anchor => {
      anchor.addEventListener("click", function (e) {
        e.preventDefault();

        document.querySelector(this.getAttribute("href")).scrollIntoView({
          behavior: "smooth"
        });
      });
    });
  });
</script>

  </head>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  <body class="home">
    <nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
      <div class="container -lg p-0">
        <a class="navbar-brand-img" href="#">
          <%= image_tag('site_logo_orange.png', alt: 'site logo') %>
        </a>
        <a class="site-title" href="#">Move and Groove</a> 
  
       
        <button class="navbar-toggler" class="navbar-content" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"style="padding-left: 0px;"></span>
        </button>

        
      <div class="collapse navbar-collapse ml-auto" id="navbarNav">
                <ul class="navbar-nav ml-auto justify-content-end">
                  <li class="nav-item">
                    <%= link_to 'Home', root_path, class: 'nav-link' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to 'About', '#about', class: 'nav-link' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to 'Dashboard', activities_path, class: 'nav-link' %>
                  </li>
                </ul>
        
      <div class="user-actions ml-auto">
        <% if user_signed_in? %>
          <div class="user-dropdown">
            <button class="user-dropdown-btn">
              Welcome <%= current_user.email %>
              <span>&#9662;</span>
            </button>
            <div class="user-dropdown-content">
              <%= link_to 'Profile', edit_user_registration_path, class: 'dropdown-link' %>
              <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class: 'sign-out-btn' %>
            </div>
          </div>
        <% else %>
          <%= button_to 'Sign in', new_user_session_path, class: 'sign-in-btn' %>
        <% end %>
      </div>
      </div>
      </div>
    </nav>
    <%= yield %>
  </body>
 <footer class="site-footer" id="bootstrap-overrides">
      <div class="container1">
        <div class="row">
          <div class="col-sm-12 col-md-6">
            <a class="navbar-brand-footer" href="#">
            <%= image_tag('site_logo_white.png', alt: 'site logo') %>
            </a>
          </div>

          <div class="col-xs-6 col-md-3">
           <h6>Connect</h6>
            <ul class="footer-links">
              <li><%= link_to 'Log in', new_user_session_path %></li>
              </ul>
          </div>

          <div class="col-xs-6 col-md-3">
            <h6>Quick Links</h6>
            <ul class="footer-links">
              <li><%= link_to 'Home', root_path %></li>
              <li><%= link_to 'About', '#about' %></li>
              <li><%= link_to 'Dashboard', activities_path %></li>
              <li><a href="#">Privacy Policy</a></li>
            </ul>
          </div>

        </div>
        <hr>
      </div>
      <div class="container1">
        <div class="row">
          <div class="col-md-8 col-sm-6 col-xs-12">
            <p class="copyright-text">Copyright &copy; 2024 All Rights Reserved by 
         <a href="#">Move and groove</a>.
            </p>
          </div>

<div class="col-md-4 col-sm-6 col-xs-12">
  <ul class="social-icons">
    <li>
      <a class="facebook" href="#">
        <div class="social-icon">
          <%= image_tag('fb_logo.png', alt: 'Facebook') %>
        </div>
      </a>
    </li>
    <li>
      <a class="instagram" href="#">
        <div class="social-icon">
          <%= image_tag('Instagram_logo.png', alt: 'Instagram') %>
        </div>
      </a>
    </li>

</div>

        </div>
      </div>
</footer>


</html>